import ClassesImage from "../../assets/about_1_.jpg";
const classesDetails = [
  {
    id: 1,
    img: ClassesImage,
    url: "/Writing",
    urlText: "Writing",
    header: "Nursery One",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in writing",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "See All",
    urlPath: "/Featured",
  },
  {
    id: 2,
    img: ClassesImage,
    url: "/Writing",
    urlText: "Mathematics",
    header: "Nursersery Two",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "Featured",
    urlPath: "/Featured",
  },
  {
    id: 3,
    img: ClassesImage,
    url: "/Writing",
    urlText: "English Language",
    header: "Primary One",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in English",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "Featured",
    urlPath: "/Featured",
  },
  {
    id: 4,
    img: ClassesImage,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "Featured",
    urlPath: "/Featured",
  },
  {
    id: 5,
    img: ClassesImage,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "Featured",
    urlPath: "/Featured",
  },
  {
    id: 6,
    img: ClassesImage,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "Popularity",
    urlPath: "/Popularity",
  },
  {
    id: 7,
    img: ClassesImage,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "Featured",
    urlPath: "/Featured",
  },
  {
    id: 8,
    img: ClassesImage,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "Popularity",
    urlPath: "/Popularity",
  },
  {
    id: 9,
    img: ClassesImage,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "Trending",
    urlPath: "/Trending",
  },
  {
    id: 10,
    img: ClassesImage,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "Trending",
    urlPath: "/Trending",
  },
  {
    id: 11,
    img: ClassesImage,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "Trending",
    urlPath: "/Trending",
  },
  {
    id: 12,
    img: ClassesImage,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "Trending",
    urlPath: "/Trending",
  },
  {
    id: 13,
    img: ClassesImage,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "Trending",
    urlPath: "/Trending",
  },
  {
    id: 14,
    img: ClassesImage,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "Popularity",
    urlPath: "/Popularity",
  },
  {
    id: 15,
    img: ClassesImage,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
    category: "Popularity",
    urlPath: "/Popularity",
  },
];

export default classesDetails;

/* import ClassesImageOne from "../../assets/class_img_4.jpg";
export const classesDetailsOne = [
  {
    id: 1,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 2,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 3,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 4,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 5,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 6,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 7,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 8,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 9,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 10,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 11,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 12,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 13,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 14,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 15,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
];

import ClassesImageTwo from "../../assets/class_img_4.jpg";
export const classesDetailsTwo = [
  {
    id: 1,
    img: ClassesImageTwo,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 2,
    img: ClassesImageTwo,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 3,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 4,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 5,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 6,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 7,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 8,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 9,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 10,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 11,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 12,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 13,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 14,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
  {
    id: 15,
    img: ClassesImageOne,
    url: "/Writing",
    urlText: "Writing",
    header: "Imagination Classes",
    time: "Class Time : 08:00 am - 10:00 am",
    info: "We ensure your child becomes really good in mathematics",
    size: {
      childClass: "Class Size :",
      classSize: " 30 - 40",
    },
    age: {
      years: "Years Old :",
      yearsAge: " 15 - 20",
    },
  },
]; */
